apiVersion: v1
kind: Service
metadata:
  name: db-service
  namespace: db-namespace
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port:   27017
      targetPort:   27017
